# Generated by Django 5.2.5 on 2025-10-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='Transaction_id',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
