# Generated by Django 5.2.5 on 2025-10-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_wishlistitem_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='Transaction_id',
        ),
    ]
