# Generated by Django 5.2.5 on 2025-10-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_seller_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
