# Generated by Django 5.2.5 on 2025-10-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Transaction_id',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
