# Generated by Django 5.2.5 on 2025-10-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
