# Generated by Django 5.2.5 on 2025-10-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_seller_shop_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
